version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: tm_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: taskdb
      MYSQL_USER: tmuser
      MYSQL_PASSWORD: tmpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: ./app
    container_name: tm_php
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_NAME: taskdb
      DB_USER: tmuser
      DB_PASS: tmpass
    volumes:
      - ./app:/var/www/html:cached

volumes:
  db_data:
